### ISSUE TITLE
v5 573g DSDT with HD screen

### ISSUE THREAD

**Issue by ghost** [Kaijun/Acer-V5-573g-DSDT#1]
[DSDT:SSDT.zip](https://github.com/Kaijun/Acer-V5-573g-DSDT/files/330140/DSDT.SSDT.zip)
Do yon know why I have 7 SSDT?
Do I need them all?
Please see atchment.

Thank you in advance.

**Comment by Kaijun** [comment]
I just help @michaelspeed to fix his DSDT/SSDTs. He owns 8 SSDTs, SSDT0-7. But only 5-7 are meaningful for us. 0-4 are all about CPU, which means you can simply drop them and generate a SSDT for your own CPU by using ssdtPRGen.sh : Check [here](https://github.com/Kaijun/Acer-V5-573g-DSDT/blob/master/README.md#ssdt-generation)

**Comment by Kaijun** [comment]
your DSDT/SSDT structure seems same as his. But the size of yours are slightly different.

You can follow my tutorial, if you need help, let me know

**Comment by Kaijun** [comment]
I updated the README. DSDT/SSDTs structures of different models are described. Check!

**Comment by ghost** [comment]
@Kaijun 
Thank you.
Now I'm patching my DSDT and I noticed that you applied  SB3 _PRW 0x6D Skylake not SB3 _PRW 0x6D.
Cuz  you can find in SB3 _PRW 0x6D
Name(_PRW, Package() { 0x6D, 0 }) end;

And in your DSDT I can find - same as in Skylake patch
Method(_PRW) { Return(Package() { 0x6D, 0 }) } end;

Correct me if I'm wrong.

**Comment by Kaijun** [comment]
u r right, i might have applied wrong patch by mistake!

virusak notifications@github.com于2016年6月23日周四 下午6:12写道：

> @Kaijun https://github.com/Kaijun
> Thank you.
> Now I'm patching my DSDT and I noticed that you applied SB3 _PRW 0x6D
> Skylake not SB3 _PRW 0x6D.
> Cuz in you can find in SB3 _PRW 0x6D
> Name(_PRW, Package() { 0x6D, 0 }) end;
> And in your DSDT I can find - same as in Skylake patch
> Method(_PRW) { Return(Package() { 0x6D, 0 }) } end;
> 
> Correct me if I'm wrong.
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/Kaijun/Acer-V5-573g-DSDT/issues/1#issuecomment-228101451,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABnVY4eXTlQye0TxREQYLIpSvIHMK6Yrks5qOrCBgaJpZM4I83Lo
> .
> 
> ## 

Herzliche Grüße / Best regards,

Kaijun Chen

**Comment by ghost** [comment]
Sorry for disturbing you:
9 Brightness Keys (**\* Only for Synaptics with VoodooPS2 ***) - this patch doesn't work?

Also you can fix a typo -  Don't Apple the Patch below!  - Apply

**Comment by Kaijun** [comment]
Last time when i was still on Mavericks + Bois 2.26, i already tracked code of the fn+up/down key by following the [tutorial](http://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/). The patch you saw was from that old time.
Now it seems that the code of the fn keys has been changed since i updated my bios. And I'm also not able to track the code anymore. I don't know why... Maybe it's related to the BIOS or El Capitan.

**Comment by Kaijun** [comment]
@virusak if your touchpad vendor is synaptics and u r using VoodooPS2, then the brightness keys are already fixed. Check the newest release.
Fn+Left / Right are working now 🎉

**Comment by Kaijun** [comment]
@virusak if you need help, please let me know!

**Comment by Kaijun** [comment]
@virusak I just adjusted the flow of the tutorial and wrote some patches to ease the whole procedure. now we have a more simple patch flow. 
Your Keys should be same as mine. You can simply apply my patch and see if works.
If not, follow the http://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/

Basically you should:
- install ACPIDebug.kext: https://github.com/RehabMan/OS-X-ACPI-Debug
- patch **`OS Check Fix (windows 8)`** -> `Add DSDT Debug Methods` -> `Instrument EC Queries`
- reboot & open `Console.App` monitor system.log as you press your brightness keys
