### ISSUE TITLE
How did you figure that out.

### ISSUE THREAD

**Issue by cloud1250x4** [Kaijun/Acer-V5-573g-DSDT#2]
Hi, i had a problem with my laptop not shutting down... not even close to the same laptop as yours...

but the only thing that worked... is your shutdown fix... how did you figure it out?

Thank you!

**Comment by Kaijun** [comment]
Hmm, actually it's really simple. Just go dig through all the related threads in the hackintosh forums 😄  and try all solutions out, and see if this solution helps 🤣

**Comment by cloud1250x4** [comment]
ah xD well it helped my 7500U envy laptop soo thank you! i have no clue why i needed your shutdown fix since it looks like its from another era (rehabman kept saying i didnt need any shutdown fix lol)

and none of the easy accessible shutdown fix worked :'(

**Comment by Kaijun** [comment]
hmm, sometimes it depends. If you choose the right PowerManagement (for example KernelPM) or in some situations, you have to upgrade your [`Management-Engine-Firmware`](https://github.com/Kaijun/Acer-V5-573G-Hackintosh/tree/master/Management-Engine-Firmware) (with which i also did some experiments to improve my laptop's PM), then you probably don't need any fix for shutdowm

**Comment by cloud1250x4** [comment]
welll i just updated my ME Firmware ;) 

no change i still need your shutdown fix... but hey it's working for now.. so i'll focus on it more... when it stop working aha

Thank you for everything and have a nice day :)
